default_stages: [commit]
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-xml
  - id: check-json
  - id: pretty-format-json
  - id: check-yaml
  - id: check-toml
  - id: detect-private-key
  - id: check-case-conflict
  - id: check-docstring-first
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.8.2
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/psf/black
  rev: 22.8.0
  hooks:
  - id: black

- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
